In [1]:
# Guided by Andrej Karpathy: https://www.youtube.com/watch?v=kCc8FmEb1nY
# Thus spoke zarathustra concatenated with Dostoyevsky's 'The Idiot'

with open('TSZ_input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [2]:
print("character count: ", len(text))

print(text[:1000])

character count:  2020697
Title: Thus Spake Zarathustra
       A Book for All and None

“Zarathustra” is my brother’s most personal work; it is the history of
his most individual experiences, of his friendships, ideals, raptures,
bitterest disappointments and sorrows. Above it all, however, there
soars, transfiguring it, the image of his greatest hopes and remotest
aims. My brother had the figure of Zarathustra in his mind from his very
earliest youth: he once told me that even as a child he had dreamt of
him. At different periods in his life, he would call this haunter of his
dreams by different names; “but in the end,” he declares in a note on
the subject, “I had to do a PERSIAN the honour of identifying him with
this creature of my fancy. Persians were the first to take a broad and
comprehensive view of history. Every series of evolutions, according
to them, was presided over by a prophet; and every prophet had his
‘Hazar,’--his dynasty of a thousand years.”

All Zarathustra’s views

In [3]:
chars = sorted(list(set(text)))
vocab_size = len(chars)

# chars = [c for c in chars if c != 'É' and  c != 'à' and c != 'ç' and c != 'è' and c != 'é' and c != 'ê']

print(''.join(chars))
print(vocab_size)



 !"$%'()*,-./0123456789:;?ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_abcdefghijklmnopqrstuvwxyzÉàçèéê—‘’“”
93


In [4]:
# Tokenization, char to int

# In practice a subword tokenization is used, where the size of the available tokens is larger but the list of ints representing a string is shorter
stoi = {c:i for i,c in enumerate(chars)}
itos = {i:c for i,c in enumerate(chars)}

encode = lambda s: [stoi[c] for c in s]
decode = lambda w: ''.join([itos[i] for i in w])

In [5]:
import tensorflow as tf
import numpy as np
data = encode(text)
data = np.array(data)

train_split = int(len(data) * 0.9)
xtrain = data[:train_split]
val_data = data[train_split:]
# data = tf.Tensor(data, 0,dtype=tf.int64)

In [6]:
chunk_size = 8
xtrain[:chunk_size+1]

array([46, 64, 75, 67, 60, 24,  1, 46, 63])

In [7]:
x = xtrain[:chunk_size]
y = xtrain[1:chunk_size+1]

# transformer will never receive more than chunk_size tokens/inputs at a time
# The below operation is not only done for efficiency but also so the transformer is 'used' to seeing context of size 1..chunk_size
for k in range(chunk_size):
    context = x[:k+1]
    target = y[k]
    print(f'context: {context} target: {target}')

context: [46] target: 64
context: [46 64] target: 75
context: [46 64 75] target: 67
context: [46 64 75 67] target: 60
context: [46 64 75 67 60] target: 24
context: [46 64 75 67 60 24] target: 1
context: [46 64 75 67 60 24  1] target: 46
context: [46 64 75 67 60 24  1 46] target: 63


In [8]:
tf.random.set_seed(4646)
batch_size = 4
chunk_size = 8
def get_batch(dat):
    dat = xtrain if dat == 'train' else val_data
    randint = tf.random.uniform(shape=(batch_size,), minval=0, maxval=len(dat)-chunk_size-1, dtype=tf.int64)
    x = tf.stack([dat[i:i+chunk_size] for i in randint])
    y = tf.stack([dat[i+1:i+chunk_size+1] for i in randint])
    # print(f"randint: {randint}, randint.shape: {randint.shape}")
    return x,y

xs, ys = get_batch('train')
print('inputs:')
print(xs.shape)
print(xs)
print('targets:')
print(ys.shape)
print(ys)
"""
x=[1,60,69..10]
y = [60,69,..1]
input x[0,0:2]= [1,60] output is y[2] = 69
"""

print('()_________()')

for b in range(batch_size):
    for k in range(chunk_size):
        context = xs[b,:k+1]
        target = ys[b,k]
        print(f'context: {context} target: {target}')


inputs:
(4, 8)
tf.Tensor(
[[ 1 60 69 70 76 62 63 10]
 [73  1 75 63 60  1 67 56]
 [78 60 77 60 73 11 11 63]
 [67 80  1 64 69  1 56  1]], shape=(4, 8), dtype=int32)
targets:
(4, 8)
tf.Tensor(
[[60 69 70 76 62 63 10  1]
 [ 1 75 63 60  1 67 56 74]
 [60 77 60 73 11 11 63 70]
 [80  1 64 69  1 56  1 58]], shape=(4, 8), dtype=int32)
()_________()
context: [1] target: 60
context: [ 1 60] target: 69
context: [ 1 60 69] target: 70
context: [ 1 60 69 70] target: 76
context: [ 1 60 69 70 76] target: 62
context: [ 1 60 69 70 76 62] target: 63
context: [ 1 60 69 70 76 62 63] target: 10
context: [ 1 60 69 70 76 62 63 10] target: 1
context: [73] target: 1
context: [73  1] target: 75
context: [73  1 75] target: 63
context: [73  1 75 63] target: 60
context: [73  1 75 63 60] target: 1
context: [73  1 75 63 60  1] target: 67
context: [73  1 75 63 60  1 67] target: 56
context: [73  1 75 63 60  1 67 56] target: 74
context: [78] target: 60
context: [78 60] target: 77
context: [78 60 77] target: 60
context: [7

In [23]:
# def ngram(n, data):
#     return [data[i:i+n] for i in range(len(data)-n+1)]
# tf.keras.layers.TextVectorization(...)?
# xs.numpy()

array([[ 1, 60, 69, 70, 76, 62, 63, 10],
       [73,  1, 75, 63, 60,  1, 67, 56],
       [78, 60, 77, 60, 73, 11, 11, 63],
       [67, 80,  1, 64, 69,  1, 56,  1]])

In [41]:
from tensorflow import keras
# import keras.backend as K

# N-gram language model https://web.stanford.edu/~jurafsky/slp3/3.pdf
class ngramLangModel(keras.layers.Layer):
    def __init__(self, vocab_size):
        # `super` call to inherit from keras.layers.Layer
        super(ngramLangModel, self).__init__()

        self.token_embedding = keras.layers.Embedding(vocab_size, vocab_size)
    # state init
    def build(self, input_shape):
        pass

    # every row from input xs will refer to embedding table, and index a row that corresponds to the token
    # need to be arranged in a (Batch, Time, Channel?) format --> (4,8,vocab_size)
    def call(self, xss, targets):
        logits = self.token_embedding(xss)
        # from logits to normalized probabilities
        # CategoricalCrossentropy expects labels to be provided in a one hot rep, labels as ints use SparseCategoricalCrossentropy
        """
        # Figure out dimensions

        loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True)
        B, T, C = logits.shape
        logits = logits.reshape(-1)
        targets = targets.reshape(-1)
        """

        # self.add_loss(loss(logits, targets))
        return logits

b = ngramLangModel(vocab_size)
out = b(xs, ys)
out.shape

TensorShape([4, 8, 93])

In [30]:
# train on gpu
# with tf.device('/GPU:0'):
#     model = get_model()
#     model.compile()
#     model.fit()